--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/J1b1x/FunctionalItem
build-by-default: true
branches:
- master
projects:
  FunctionalItem:
    path: ""
    model: virion
    type: library
...
